### ISSUE TITLE
Add support for queries on to-many relationships

### ISSUE THREAD

**Issue by jimix** [jimix/CDTIncrementalStore#4]
@mkistler filed this originally [here](/jimix/CDTDatastore/issues/34)
CoreData supports [filter predicates for a to-many relationship](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CoreData/Articles/cdBindings.html#//apple_ref/doc/uid/TP40004194-SW5).

This basically means that the predicate specifies a condition on an attribute in an entity related to the root entity by a to-many relationship.  The attribute is specified with dotted notation: _relationship_name_._attribute_name_.

Note: CloudantQuery allows querying into subdocuments, but relationships are not implemented using subdocuments.

**Comment by mkistler** [comment]
Closing old issue.
