### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by jimix** [jimix/CDTIncrementalStore#5]
@mkistler files this original bug [here](jimix/CDTDatastore/issues/40)
I think we should revise the documentation to organize the basic usage information first, with the details of the information later. We should also clearly indicate features that are supported and not supported (similar to query.md).

**Comment by mkistler** [comment]
Jimi ... I think you addressed this issue in [commit 6004745](https://github.com/jimix/CDTIncrementalStore/commit/6004745866ab16e78ab725ca7300586d50a2e5d6#diff-04c6e90faac2675aa89e2176d2eec7d8).  Agreed?

If so, how do mark this issue to indicate that?

**Comment by jimix** [comment]
@mkistler, yes I agree, this was resolved by 6004745.
(BTW: you can just type the SHA and it will make the link automajically, then click "Close and comment")
